In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Introduction to Tensors

In [ ]:
#Creating scalars
scalar = torch.tensor(8)
scalar.ndim #scalars have no dimensions

#Get scalar as Python integer
scalar.item()



8

In [ ]:
#Creating vectors

vector = torch.tensor([7,7])
vector.ndim # vectors has dimensions greater than or equal to 1 (number of pairs of brackets)
vector.shape #the number of elements


torch.Size([2])

In [ ]:
#Creating matrices

MATRIX = torch.tensor([[7,7],
                      [8,8],])

MATRIX.ndim
MATRIX[0] #accessing items in matrices similar to array 
MATRIX[1]
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#Creating tensors

TENSOR = torch.tensor([[[1,2,3,4],
                        [4,5,6,4],
                        [7,8,9,4]],
                       [[1,2,3,4],
                        [4,5,6,4],
                        [7,8,9,4]],])

TENSOR.ndim
TENSOR.shape

torch.Size([2, 3, 4])

### Random tensors


In [ ]:
#Create random tensor with of tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor 


tensor([[0.9447, 0.4934, 0.5755, 0.1343],
        [0.1258, 0.3062, 0.5892, 0.6148],
        [0.0445, 0.8260, 0.1258, 0.7959]])

In [ ]:
 #Create random tensor with shape similar to image tensor

 random_image_size_tensor = torch.rand(size = (3, 224, 224)) #height, width, color channels (RGB)
 random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones Tensors

In [ ]:
#Creating an all-zero tensor
zeros = torch.zeros(3,4)
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [ ]:
ones = torch.ones(3,4)
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### Range of Tensors and tensors-like

In [ ]:
#Creating range of tensors
one2ten = torch.arange(start = 1,end = 10, step = 1)
one2ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Creating tensors like

ten_zeros = torch.zeros_like(input = one2ten)
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
ten_ones = torch.ones_like(input = one2ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1])

## Tensor Datatypes


In [ ]:
#Creating tensors with different datatypes

# datatype is essential to precision in computing 
# default tensor datatype is float32 even if set to None
float32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                              dtype = None, #datatype of tensor
                              device = None, #cpu or gpu
                              requires_grad = False) #whether or not to track gradience with calculations 

#
float32_tensor, float32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [ ]:
float16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.float16) 

float16_tensor, float16_tensor.dtype



(tensor([3., 6., 9.], dtype=torch.float16), torch.float16)

In [ ]:
float16_tensor = float32_tensor.type(torch.float16)

float16_tensor, float16_tensor.dtype

(tensor([3., 6., 9.], dtype=torch.float16), torch.float16)

### Tensor Attributes

In [ ]:
#Create some tensor

some_tensor = torch.rand(4,3)

print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on: {some_tensor.device}')

tensor([[0.9242, 0.9462, 0.8871],
        [0.0035, 0.6905, 0.7639],
        [0.8581, 0.9169, 0.8354],
        [0.2214, 0.0164, 0.9725]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([4, 3])
Device tensor is on: cpu


### Tensor Operations
(element - wise)
- Addition
- Subtraction
- Multiplication (element - wise)
- Division

By Matrix
- Matrix Multiplication

In [ ]:
# Tensor Operation (element - wise)

tensor = torch.tensor([1,2,3])
print(tensor + 10) #addition torch.add
print(tensor - 10) #subtraction torch.sub
print(tensor * 10) #multiplication torch.mul
print(tensor / 10) #division torch.div

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])


In [ ]:
# Matrix Multiplication (dot product)
print(torch.matmul(tensor, tensor)) #can also be torch.mm()

tensor(14)


### Tensor Aggregation

In [ ]:
#Create a tensor
range_tensor = torch.arange(0,1000,100)
print(torch.min(range_tensor), range_tensor.min()) #finding min value in tensor
print(torch.max(range_tensor), range_tensor.max()) #finding max value in tensor
print(torch.mean(range_tensor.type(torch.float32)), range_tensor.type(torch.float32).mean()) #mean of tensor (has to be float32 datatype)
print(torch.sum(range_tensor), range_tensor.sum()) #sum of all the items in range_tensor

tensor(0) tensor(0)
tensor(900) tensor(900)
tensor(450.) tensor(450.)
tensor(4500) tensor(4500)


In [ ]:
#Create a tensor
range_tensor = torch.arange(0,1000,100)
print(torch.argmin(range_tensor), range_tensor.argmin()) #finding index of min value in tensor
print(torch.argmax(range_tensor), range_tensor.argmax()) #finding index of max value in tensor


tensor(0) tensor(0)
tensor(9) tensor(9)
tensor(450.) tensor(450.)
tensor(4500) tensor(4500)


### Reshsaping, viewing, stacking, squeezing, unsqueezing, permuting tensors

- Reshaping - change shape (reshape) tensor to desired shape
- Viewing - return view of intput tensor at certain shape but retain memory location
- Stacking - combining multiple tensors horizontally, vertically, etc.
- Squeeze - removes 1 dimension to tensor
- Unsqueeze - adds 1 dimension to tensor
- Permute - return view of tensor with dimensions swapped in certain way

In [ ]:
#reimport tensor to avoid rerunning all cells
import torch

range_tensor1 = torch.arange(0., 100., 10.)
print(range_tensor1, range_tensor1.shape)

#Reshape (compatible with original shape (factor of original shape))

print(torch.reshape(range_tensor1, (1,2,5)), torch.reshape(range_tensor1, (10,1))) #can also be range_tensor1.reshape(enter desired shape)

#Change view (will affect the original if values are changed etc.)
print(range_tensor1.view(1,2,5), range_tensor1.view(10,1)) 

#Stack the tensors
range_stacked = torch.stack([torch.arange(10),torch.arange(10),torch.arange(10)], dim = 0)
print(range_stacked, range_stacked.shape)

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.]) torch.Size([10])
tensor([[[ 0., 10., 20., 30., 40.],
         [50., 60., 70., 80., 90.]]]) tensor([[ 0.],
        [10.],
        [20.],
        [30.],
        [40.],
        [50.],
        [60.],
        [70.],
        [80.],
        [90.]])
tensor([[[ 0., 10., 20., 30., 40.],
         [50., 60., 70., 80., 90.]]]) tensor([[ 0.],
        [10.],
        [20.],
        [30.],
        [40.],
        [50.],
        [60.],
        [70.],
        [80.],
        [90.]])
tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]) torch.Size([3, 10])


In [ ]:
#Squeeze tensor - 
print(range_stacked.squeeze(), range_stacked.squeeze().shape)
print(torch.reshape(range_tensor1, (1,2,5)).squeeze(), torch.reshape(range_tensor1, (1,2,5)).squeeze().shape)
      
#Unsqueeze
print(range_stacked.unsqueeze(dim = 0), range_stacked.unsqueeze(dim = 0).shape)
print(range_stacked.unsqueeze(dim = 1), range_stacked.unsqueeze(dim = 1).shape)

#Permute
pic_original = torch.rand(3, 234,244)
print(pic_original, pic_original.shape)
print(pic_original.permute(1, 2, 0), pic_original.permute(1, 2, 0).shape )

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]) torch.Size([3, 10])
tensor([[ 0., 10., 20., 30., 40.],
        [50., 60., 70., 80., 90.]]) torch.Size([2, 5])
tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
         [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
         [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]]) torch.Size([1, 3, 10])
tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],

        [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],

        [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]]) torch.Size([3, 1, 10])
tensor([[[0.9607, 0.8418, 0.4961,  ..., 0.6564, 0.8995, 0.6046],
         [0.8808, 0.9563, 0.3376,  ..., 0.3903, 0.4363, 0.6506],
         [0.2374, 0.6531, 0.4389,  ..., 0.4905, 0.4275, 0.7955],
         ...,
         [0.4262, 0.9654, 0.8602,  ..., 0.6150, 0.9231, 0.9724],
         [0.1236, 0.8010, 0.6414,  ..., 0.6184, 0.0571, 0.5528],
         [0.3220, 0.8116, 0.2257,  ..., 0.4475, 0.8720, 0.8069]],

        [[0.9422, 0.1662, 0.2687,  ..., 0.4367, 0.6397, 0.3090]

### Tensor Indexing

In [ ]:
# Create tensor
tensor = torch.arange(1,10).reshape(1,3,3)
print(tensor, tensor.shape)
print(tensor[0], tensor[0][0], tensor[0][0][0])
print(tensor[0,1,:])


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) tensor([1, 2, 3]) tensor(1)
tensor([4, 5, 6])


### Tensors with Numpy

In [5]:
import torch
import numpy as np

In [9]:
# Numpy to Tensor

p_array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(np_array) #in float64 since default type for numpy is float64
print(np_array, tensor)

[1. 2. 3. 4. 5. 6. 7.] tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [11]:
#Tensor to Numpy
tensor = torch.arange(1.,8.)
np_array = tensor.numpy() #in float32 since default dtype for tensor is float32
print(tensor, np_array)

tensor([1., 2., 3., 4., 5., 6., 7.]) [1. 2. 3. 4. 5. 6. 7.]
