<a href="https://colab.research.google.com/github/ninyx/PyTorch/blob/master/Pytorch_Setup.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Setting up Colab for PyTorch

### Check available GPU

In [1]:
!nvidia-smi

Thu Apr 13 23:20:44 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P8    12W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### Check GPU Access for PyTorch

In [7]:
import torch
import numpy as np

torch.cuda.is_available()

True

In [3]:
#Set up device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

### Putting tensors and models in GPU

In [9]:
#Create tensor in CPU
tensor = torch.tensor([1,2,3])

#Check device of tensor
print(tensor, tensor.device)

#Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu)

#Move it back to CPU
tensor_on_cpu = tensor_on_gpu.cpu().numpy()
print(tensor_on_cpu)

tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0')
tensor([1, 2, 3])


tensor([1, 2, 3], device='cuda:0')
