In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Introduction to Tensors

In [2]:
#Creating scalars
scalar = torch.tensor(8)
scalar.ndim #scalars have no dimensions

#Get scalar as Python integer
scalar.item()



8

In [3]:
#Creating vectors

vector = torch.tensor([7,7])
vector.ndim # vectors has dimensions greater than or equal to 1 (number of pairs of brackets)
vector.shape #the number of elements


torch.Size([2])

In [4]:
#Creating matrices

MATRIX = torch.tensor([[7,7],
                      [8,8],])

MATRIX.ndim
MATRIX[0] #accessing items in matrices similar to array 
MATRIX[1]
MATRIX.shape

torch.Size([2, 2])

In [5]:
#Creating tensors

TENSOR = torch.tensor([[[1,2,3,4],
                        [4,5,6,4],
                        [7,8,9,4]],
                       [[1,2,3,4],
                        [4,5,6,4],
                        [7,8,9,4]],])

TENSOR.ndim
TENSOR.shape

torch.Size([2, 3, 4])

### Random tensors


In [6]:
#Create random tensor with of tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor 


tensor([[0.9447, 0.4934, 0.5755, 0.1343],
        [0.1258, 0.3062, 0.5892, 0.6148],
        [0.0445, 0.8260, 0.1258, 0.7959]])

In [7]:
 #Create random tensor with shape similar to image tensor

 random_image_size_tensor = torch.rand(size = (3, 224, 224)) #height, width, color channels (RGB)
 random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones Tensors

In [8]:
#Creating an all-zero tensor
zeros = torch.zeros(3,4)
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [9]:
ones = torch.ones(3,4)
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### Range of Tensors and tensors-like

In [10]:
#Creating range of tensors
one2ten = torch.arange(start = 1,end = 10, step = 1)
one2ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
#Creating tensors like

ten_zeros = torch.zeros_like(input = one2ten)
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
ten_ones = torch.ones_like(input = one2ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1])

## Tensor Datatypes


In [13]:
#Creating tensors with different datatypes

# datatype is essential to precision in computing 
# default tensor datatype is float32 even if set to None
float32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                              dtype = None, #datatype of tensor
                              device = None, #cpu or gpu
                              requires_grad = False) #whether or not to track gradience with calculations 

#
float32_tensor, float32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [14]:
float16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.float16) 

float16_tensor, float16_tensor.dtype



(tensor([3., 6., 9.], dtype=torch.float16), torch.float16)

In [15]:
float16_tensor = float32_tensor.type(torch.float16)

float16_tensor, float16_tensor.dtype

(tensor([3., 6., 9.], dtype=torch.float16), torch.float16)

### Tensor Attributes

In [16]:
#Create some tensor

some_tensor = torch.rand(4,3)

print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on: {some_tensor.device}')

tensor([[0.9242, 0.9462, 0.8871],
        [0.0035, 0.6905, 0.7639],
        [0.8581, 0.9169, 0.8354],
        [0.2214, 0.0164, 0.9725]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([4, 3])
Device tensor is on: cpu


### Tensor Operations
(element - wise)
- Addition
- Subtraction
- Multiplication (element - wise)
- Division

By Matrix
- Matrix Multiplication

In [17]:
# Tensor Operation (element - wise)

tensor = torch.tensor([1,2,3])
print(tensor + 10) #addition torch.add
print(tensor - 10) #subtraction torch.sub
print(tensor * 10) #multiplication torch.mul
print(tensor / 10) #division torch.div

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])


In [18]:
# Matrix Multiplication (dot product)
print(torch.matmul(tensor, tensor)) #can also be torch.mm()

tensor(14)


### Tensor Aggregation

In [22]:
#Create a tensor
range_tensor = torch.arange(0,1000,100)
print(torch.min(range_tensor), range_tensor.min()) #finding min value in tensor
print(torch.max(range_tensor), range_tensor.max()) #finding max value in tensor
print(torch.mean(range_tensor.type(torch.float32)), range_tensor.type(torch.float32).mean()) #mean of tensor (has to be float32 datatype)
print(torch.sum(range_tensor), range_tensor.sum()) #sum of all the items in range_tensor

tensor(0) tensor(0)
tensor(900) tensor(900)
tensor(450.) tensor(450.)
tensor(4500) tensor(4500)


In [24]:
#Create a tensor
range_tensor = torch.arange(0,1000,100)
print(torch.argmin(range_tensor), range_tensor.argmin()) #finding index of min value in tensor
print(torch.argmax(range_tensor), range_tensor.argmax()) #finding index of max value in tensor


tensor(0) tensor(0)
tensor(9) tensor(9)
tensor(450.) tensor(450.)
tensor(4500) tensor(4500)


### Reshsaping, viewing, stacking, squeezing, unsqueezing, permuting tensors

- Reshaping - change shape (reshape) tensor to desired shape
- Viewing - return view of intput tensor at certain shape but retain memory location
- Stacking - combining multiple tensors horizontally, vertically, etc.
- Squeeze - removes 1 dimension to tensor
- Unsqueeze - adds 1 dimension to tensor
- Permute - return view of tensor with dimensions swapped in certain way

In [7]:
#reimport tensor to avoid rerunning all cells
import torch

range_tensor1 = torch.arange(0., 100., 10.)
print(range_tensor1, range_tensor1.shape)

#Reshape (compatible with original shape (factor of original shape))

print(torch.reshape(range_tensor1, (1,2,5)), torch.reshape(range_tensor1, (10,1))) #can also be range_tensor1.reshape(enter desired shape)

#Change view (will affect the original if values are changed etc.)
print(range_tensor1.view(1,2,5), range_tensor1.view(10,1)) 

#Stack the tensors
range_stacked = torch.stack([torch.arange(10),torch.arange(10),torch.arange(10)], dim = 0)
print(range_stacked, range_stacked.shape)

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.]) torch.Size([10])
tensor([[[ 0., 10., 20., 30., 40.],
         [50., 60., 70., 80., 90.]]]) tensor([[ 0.],
        [10.],
        [20.],
        [30.],
        [40.],
        [50.],
        [60.],
        [70.],
        [80.],
        [90.]])
tensor([[[ 0., 10., 20., 30., 40.],
         [50., 60., 70., 80., 90.]]]) tensor([[ 0.],
        [10.],
        [20.],
        [30.],
        [40.],
        [50.],
        [60.],
        [70.],
        [80.],
        [90.]])
tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]) torch.Size([3, 10])


In [16]:
#Squeeze tensor - 
print(range_stacked.squeeze(), range_stacked.squeeze().shape)
print(torch.reshape(range_tensor1, (1,2,5)).squeeze(), torch.reshape(range_tensor1, (1,2,5)).squeeze().shape)
      
#Unsqueeze
print(range_stacked.unsqueeze(dim = 0), range_stacked.unsqueeze(dim = 0).shape)
print(range_stacked.unsqueeze(dim = 1), range_stacked.unsqueeze(dim = 1).shape)

#Permute
pic_original = torch.rand(3, 244,244)
print(pic_original, pic_original.shape)
print(pic_original.permute(1, 2, 0), pic_original.permute(1, 2, 0).shape )

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]) torch.Size([3, 10])
tensor([[ 0., 10., 20., 30., 40.],
        [50., 60., 70., 80., 90.]]) torch.Size([2, 5])
tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
         [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
         [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]]) torch.Size([1, 3, 10])
tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],

        [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],

        [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]]) torch.Size([3, 1, 10])
tensor([[[0.8586, 0.8045, 0.7228,  ..., 0.6258, 0.7700, 0.5859],
         [0.3509, 0.5674, 0.6243,  ..., 0.6281, 0.8158, 0.4374],
         [0.6642, 0.0200, 0.8798,  ..., 0.3607, 0.2043, 0.4587],
         ...,
         [0.7668, 0.6209, 0.9953,  ..., 0.5648, 0.5308, 0.5135],
         [0.8691, 0.7274, 0.4114,  ..., 0.3924, 0.8230, 0.9304],
         [0.4158, 0.4827, 0.9777,  ..., 0.4567, 0.9310, 0.6230]],

        [[0.8306, 0.3842, 0.5134,  ..., 0.8044, 0.4719, 0.3783]