In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Introduction to Tensors

In [2]:
#Creating scalars
scalar = torch.tensor(8)
scalar.ndim #scalars have no dimensions

#Get scalar as Python integer
scalar.item()



8

In [3]:
#Creating vectors

vector = torch.tensor([7,7])
vector.ndim # vectors has dimensions greater than or equal to 1 (number of pairs of brackets)
vector.shape #the number of elements


torch.Size([2])

In [4]:
#Creating matrices

MATRIX = torch.tensor([[7,7],
                      [8,8],])

MATRIX.ndim
MATRIX[0] #accessing items in matrices similar to array 
MATRIX[1]
MATRIX.shape

torch.Size([2, 2])

In [5]:
#Creating tensors

TENSOR = torch.tensor([[[1,2,3,4],
                        [4,5,6,4],
                        [7,8,9,4]],
                       [[1,2,3,4],
                        [4,5,6,4],
                        [7,8,9,4]],])

TENSOR.ndim
TENSOR.shape

torch.Size([2, 3, 4])

### Random tensors


In [6]:
#Create random tensor with of tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor 


tensor([[0.5692, 0.1835, 0.1668, 0.5658],
        [0.0364, 0.0340, 0.7525, 0.8967],
        [0.7264, 0.8436, 0.6172, 0.1475]])

In [7]:
 #Create random tensor with shape similar to image tensor

 random_image_size_tensor = torch.rand(size = (3, 224, 224)) #height, width, color channels (RGB)
 random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones Tensors

In [8]:
#Creating an all-zero tensor
zeros = torch.zeros(3,4)
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [9]:
ones = torch.ones(3,4)
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### Range of Tensors and tensors-like

In [10]:
#Creating range of tensors
one2ten = torch.arange(start = 1,end = 10, step = 1)
one2ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
#Creating tensors like

ten_zeros = torch.zeros_like(input = one2ten)
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
ten_ones = torch.ones_like(input = one2ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1])